services:
    keycloak:
      image: quay.io/keycloak/keycloak:24.0.3
      container_name: keycloak-ui-spike
      ports:
        - "8000:8080"
      volumes:
        - ./keycloak:/opt/keycloak/data/import
      networks:
        - ui-spike
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      command: -v start-dev --import-realm
networks:
    ui-spike:
      name: ui-spike-network