name: build
run-name: Build
on:
  push:
    branches-ignore: [main]
jobs:
  build-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
      - name: Set execute permissions for Gradle
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
